### PR TITLE
Integrates Hutch output with OpenSpiel.

### PR DESCRIPTION
**Pull request by karthik-ramanathan-3006**
**What's the problem?**
OpenSpiel is fed by JSON output from Explain which is like so:
```
[
  {
    "Plan": {
      "Node Type": "Sort",
      "Parallel Aware": false,
      "Async Capable": false,
      "Startup Cost": 1047.14,
      "Total Cost": 1070.73,
      "Plan Rows": 9435,
      "Plan Width": 62,
      "Sort Key": ["d.d_city"],
      "Plans": [
        {
          "Node Type": "Nested Loop",
          "Parent Relationship": "Outer",
          "Parallel Aware": false,
          "Async Capable": false,
          "Join Type": "Inner",
          "Startup Cost": 3.23,
          "Total Cost": 424.25,
          "Plan Rows": 9435,
          "Plan Width": 62,
          "Inner Unique": false,
          "Join Filter": "(o.no_w_id = w.w_id)",
          <snip>
        }
       ]
    }
  }
]         
```
while the output from Hutch (EXPLAIN (format tscout) ... ) is as follows:
```
[
  {
    "Tscout": {
      "node": "node-0",
      "tag": "ExecSort",
      "Sort_plan_type": 42,
      "Sort_plan_startup_cost": 1047.143336,
      "Sort_plan_total_cost": 1070.730836,
      "Sort_plan_plan_rows": 9435.000000,
      "Sort_plan_plan_width": 62,
      "Sort_plan_parallel_aware": false,
      "Sort_plan_parallel_safe": true,
      "Sort_plan_async_capable": false,
      "Sort_plan_plan_node_id": 0,
      "Sort_plan_targetlist": "<skipped>",
      "Sort_plan_qual": "<skipped>",
      "Sort_plan_lefttree": "<skipped>",
      "Sort_plan_righttree": "<skipped>",
      "Sort_plan_initPlan": "<skipped>",
      "Sort_plan_extParam": "<skipped>",
      "Sort_plan_allParam": "<skipped>",
      "Sort_numCols": 1,
      "Sort_sortColIdx": "<skipped>",
      "Sort_sortOperators": "<skipped>",
      "Sort_collations": "<skipped>",
      "Sort_nullsFirst": "<skipped>",
      "Plans": [
        {
          "node": "node-1",
          "tag": "ExecNestLoop",
          "NestLoop_join_plan_type": 37,
          "NestLoop_join_plan_startup_cost": 3.225000,
          "NestLoop_join_plan_total_cost": 424.253750,
          "NestLoop_join_plan_plan_rows": 9435.000000,
          "NestLoop_join_plan_plan_width": 62,
          "NestLoop_join_plan_parallel_aware": false,
          "NestLoop_join_plan_parallel_safe": true,
          "NestLoop_join_plan_async_capable": false,
          "NestLoop_join_plan_plan_node_id": 1,
          "NestLoop_join_plan_targetlist": "<skipped>",
          "NestLoop_join_plan_qual": "<skipped>",
          "NestLoop_join_plan_lefttree": "<skipped>",
          "NestLoop_join_plan_righttree": "<skipped>",
          "NestLoop_join_plan_initPlan": "<skipped>",
          "NestLoop_join_plan_extParam": "<skipped>",
          "NestLoop_join_plan_allParam": "<skipped>",
          "NestLoop_join_jointype": 0,
          "NestLoop_join_inner_unique": false,
          "NestLoop_join_joinqual": "<skipped>",
          "NestLoop_nestParams": "<skipped>",
          <snip>
          }
      ]
    }
  }
]
```

In a nutshell, the problem is that OpenSpiel expects fixed keys in JSON, while Hutch returns variably named keys.

**What's the solution?**
Three approaches were discussed to fix this problem:
1. Making changes to database.cc in OpenSpiel to do an "ends with" search to figure out the names of the keys.
2. Adding intelligence to OpenSpiel to "understand" the structure behind the name of the key
3. Adding intelligence to Hutch to spit out fixed keys.

As a first cut solution, we've implemented (1) which is what this PR addresses.

**TODO:**
~~Validate end-to-end that this doesn't break anything~~ : DONE

### CODE REVIEW

**Review by 17zhangw — CHANGES_REQUESTED** [review]
I think you also need to modify:

https://github.com/cmu-db/noisepage-pilot/blob/2841d2462ecd02c125c6e416726bb4f04a0df493/action/selection/open_spiel/database.cc#L624

such that it will get the `explain` format as provided by `hutch` rather than just JSON. Under the current setup, I believe it'll error out in `ExplainMicroserviceCost` (unless I'm mistaken otherwise).

In that case, you'll likely also need to modify `demo/mvp.sh` so it properly loads/installs Hutch as needed (there are already `doit` tasks for that). I believe we'll also need another OpenSpiel feature flag like `use_hutch` (similar to `use_hypopg`) that can ensure attempts to `EXPLAIN (FORMAT TSCOUT)` succeed.

**Comment by karthik-ramanathan-3006** [comment]
@17zhangw - With the latest changes, I've verified that nothing breaks end-to-end. 

> In that case, you'll likely also need to modify demo/mvp.sh so it properly loads/installs Hutch as needed (there are already doit tasks for that). I believe we'll also need another OpenSpiel feature flag like use_hutch (similar to use_hypopg) that can ensure attempts to EXPLAIN (FORMAT TSCOUT) succeed.

Hutch still needs to be installed manually. There is a small discrepancy between the installation process for Hutch when its installed standalone vs when it is run with `demo/mvp.sh`. Will pick this up next. 
About the flag - I thought that Hutch will be replacing the `EXPLAIN (format json)` output? Making this a flag would probably lead to a lot of if-elses in the code, both here in OpenSpiel and potentially in the build process.

**Comment by 17zhangw** [comment]
Just saw the latest diff and it makes sense to me. Thanks!
About the issue with running through `demo/mvp.sh`, does `doit noisepage_hutch_install` not work?

**Comment by karthik-ramanathan-3006** [comment]
> About the issue with running through demo/mvp.sh, does doit noisepage_hutch_install not work?
Checked and validated that this indeed works. We're good to go!

**Review by 17zhangw — APPROVED** [review]

**Pull request merged**
